apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rideservice-ns.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - rideservice-deployment.yaml
  - rideservice-service.yaml
