apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideservice
  namespace: ride-hailing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rideservice
  template:
    metadata:
      labels:
        app: rideservice
    spec:
      containers:
        - name: rideservice
          image: localhost/rideservice:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/rideservice
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
