apiVersion: v1
kind: Service
metadata:
  name: feeds-web-app
  namespace: feed
spec:
  type: ClusterIP
  selector:
    app: feeds-web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
