apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postservice-ns.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postservice-deployment.yaml
  - postservice-service.yaml
