apiVersion: v1
kind: Service
metadata:
  name: timelineservice
  namespace: feed
spec:
  type: ClusterIP
  selector:
    app: timelineservice
  ports:
    - name: http
      port: 8081
      targetPort: 8081
